[package]
name = "wy-engine"
description = "引擎整合：事件系统、焦点管理、无障碍（AccessKit）"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
wy-signal = { workspace = true }
wy-layout = { workspace = true }
wy-render = { workspace = true }
wy-text = { workspace = true }
accesskit = { workspace = true }
log = { workspace = true }
