[package]
name = "wy-app"
description = "示例应用与工具"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
wy-signal = { workspace = true }
wy-layout = { workspace = true }
wy-render = { workspace = true }
wy-text = { workspace = true }
wy-engine = { workspace = true }
